// Package tools generates WoW addons that ride only blessed paths:
// addon files in (read at /reload), SavedVariables out (written on flush),
// Config.wtf between runs. If a generated addon needs a workaround,
// the generator is wrong — not the game.
package tools

import (
	"fmt"
	"strings"
)

// File is one generated file, path relative to Interface/AddOns/.
type File struct {
	Path    string `json:"path"`
	Content string `json:"content"`
}

// Bundle is a generated addon plus the words a human needs.
type Bundle struct {
	Files []File `json:"files"`
	Notes string `json:"notes"`
}

func toc(name, notes string, savedVars []string, files ...string) string {
	var b strings.Builder
	fmt.Fprintf(&b, "## Interface: %s\n", InterfaceVersion())
	fmt.Fprintf(&b, "## Title: %s\n", name)
	fmt.Fprintf(&b, "## Notes: %s\n", notes)
	b.WriteString("## Author: wow-foraiver\n")
	if len(savedVars) > 0 {
		fmt.Fprintf(&b, "## SavedVariables: %s\n", strings.Join(savedVars, ", "))
	}
	b.WriteString(strings.Join(files, "\n") + "\n")
	return b.String()
}

// Scaffold returns a minimal addon: a TOC and an entry file with an event
// frame, ready for a vibed prompt to grow into a UI.
func Scaffold(name, notes string) Bundle {
	if notes == "" {
		notes = "Generated by wow-foraiver."
	}
	lua := fmt.Sprintf(`-- %[1]s — generated by wow-foraiver, grown by you.
local ADDON = ...

local f = CreateFrame("Frame")
f:RegisterEvent("PLAYER_LOGIN")
f:SetScript("OnEvent", function(self, event, ...)
	print("|cff33ff99" .. ADDON .. "|r loaded.")
end)
`, name)
	return Bundle{
		Files: []File{
			{Path: name + "/" + name + ".toc", Content: toc(name, notes, nil, name+".lua")},
			{Path: name + "/" + name + ".lua", Content: lua},
		},
		Notes: fmt.Sprintf("Drop the %s/ folder into Interface/AddOns/, then /reload. "+
			"The addon prints on login; grow it from there.", name),
	}
}

// DuplexKit generates the full-duplex primitive: payload.lua runs at every
// /reload (the blessed inbound path), and Report() writes results to
// SavedVariables (the blessed outbound path, flushed on logout/exit —
// pair with `wow-foraiver watch` to see flushes land).
func DuplexKit(addonName string) Bundle {
	name := addonName
	if name == "" {
		name = "Duplex"
	}
	db := name + "DB"

	core := fmt.Sprintf(`-- %[1]s — full-duplex over blessed paths only.
-- Inbound:  edit payload.lua, /reload. That file IS the request.
-- Outbound: %[2]s.report[...] lands in SavedVariables on flush.
local ADDON = ...

%[2]s = %[2]s or {}
%[2]s.report = %[2]s.report or {}

local M = {}
_G[ADDON] = M

-- Report stores a result for the outside world; seq lets a watcher tell
-- fresh answers from stale ones.
function M.Report(key, value)
	%[2]s.seq = (%[2]s.seq or 0) + 1
	%[2]s.report[key] = { seq = %[2]s.seq, at = time(), value = value }
end

-- Flush requests a logout-free SavedVariables write where the client
-- allows one; on this client a clean /reload also flushes.
function M.Flush()
	C_UI.Reload()
end
`, name, db)

	payload := fmt.Sprintf(`-- payload.lua — the request slot. Runs on every load/reload.
-- Replace this file's body and /reload; read answers from SavedVariables.
local M = _G[%q] or _G[(...)]

M.Report("hello", { msg = "duplex alive", client = GetBuildInfo() })
`, name)

	return Bundle{
		Files: []File{
			{Path: name + "/" + name + ".toc",
				Content: toc(name, "Full-duplex request/response over blessed paths.", []string{db},
					name+".lua", "payload.lua")},
			{Path: name + "/" + name + ".lua", Content: core},
			{Path: name + "/payload.lua", Content: payload},
		},
		Notes: "The loop: write payload.lua → /reload → in-game effects run → " +
			"Report() results flush to WTF/.../SavedVariables/" + name + ".lua → " +
			"`wow-foraiver watch --file <that path>` fires your hook when answers land. " +
			"No injection, no memory patching: the same doors the game opens for everyone.",
	}
}
